name: doctor_yab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.4+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_database: ^10.2.4
  # open_file: 3.2.1
  open_filex: ^4.3.2
  # open_file: 
  #   path: ../local_packages/open_file
  permission_handler: ^10.2.0
  # needs IOS Config
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^12.0.3
  # alice: ^0.2.1
    # path: local_packages/alice
    # git:
    #   url: https://github.com/mozaffari/alice.git
  intl: ^0.17.0
  firebase_crashlytics: ^3.3.4
  persian_number_utility: ^1.1.1
  shamsi_date: ^1.0.1
  url_launcher: ^6.0.3
  flutter_rating_bar: ^4.0.0
  dio_http_cache: ^0.3.0
    # path: "./local_packages/dio-http-cache-feature-nullsafety-dio4"
    #https://github.com/hurshi/dio-http-cache/pull/84
    #  git:
    #   url: https://github.com/vrtdev/dio-http-cache.git
    #   ref: feature/nullsafety-dio4
  flutter_icons: ^1.1.0
  infinite_scroll_pagination: ^3.1.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  auto_size_text: ^3.0.0
  image_cropper: ^1.4.1
  # image_picker: ^0.7.3
  image_picker: ^0.8.4+9
  pretty_dio_logger: ^1.1.1
  lottie: ^1.2.1
  dio: ^4.0.4
  flutter_phoenix: ^1.0.0
  hive_flutter: ^1.1.0
  # get_storage: 1.4.0
  # hive_flutter: 0.3.1
  hive: ^2.0.5
  flutter_svg: ^1.0.3
  flutter_easyloading: ^3.0.0
  timer_count_down: ^2.2.1
  pin_code_fields: ^7.0.0
  logger: ^1.1.0
  firebase_dynamic_links: ^5.0.15
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0

  get: ^4.6.1
  # alice: 0.3.2
  alice: 
    path: ..\local_pachages\alice

  place_picker:
    path: ..\local_pachages\locationpicker

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  path_provider: ^2.0.1
  jiffy: ^5.0.0
  loading_indicator: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  location: ^4.3.0
  firebase_database_web: ^0.2.0+3
  pinch_zoom: ^1.0.0
  sticky_headers: ^0.3.0+2
  readmore: ^2.1.0
  flutter_html: ^0.11.1
  webview_flutter: ^3.0.4
  stories_for_flutter: 
    path: ..\local_pachages\stories_for_flutter
  story_view: ^0.14.0
  socket_io_client: ^2.0.2
  feather_icons: ^1.2.0
  expandable_text: ^2.3.0


dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
# flutter_icons:
#   image_path: 'assets/app_icon.jpeg'
#   android: true
#   ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/fonts/
    - assets/svg/
    - assets/png/
    - assets/lot/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANYekan
      fonts:
        - asset: "fonts/IRANYekanRegular.ttf"
        - asset: "fonts/IRANYekanBold.ttf"
          weight: 700
        - asset: "fonts/IRANYekanExtraBold.ttf"
          weight: 900
        - asset: "fonts/IRANYekanRegular.ttf"
          weight: 400
        - asset: "fonts/IRANYekanLight.ttf"
          weight: 300
        - asset: "fonts/IRANYekanMedium.ttf"
          weight: 500

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages